### PR TITLE
Configuration and documentation update

### PR DESCRIPTION
**Pull request by Bdegraaf1234**
During building I encountered and updated some outdated sections of documentation and config files.

The api docs were not generated due to an outdated springdoc dependency
The ```security.github.client.timeout``` property was in an unsupported format
The file naming for the ```radar_is.yml``` file was inconsistent with hardcoded values
some formatting issues and old versions referenced in the readme

### CODE REVIEW

**Review by blootsvoets — COMMENTED** [review]
LGTM. Do you know why CI is failing?

**Comment by Bdegraaf1234** [comment]
I had a look but cannot figure it out yet.

it is related to the MPOAuthHelper.java class, it cannot authenticate properly.

```
Caused by: java.lang.ExceptionInInitializerError: Exception org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8081/oauth/token": Connection refused: connect [in thread "Test worker"]
	...
        at app//org.radarbase.appserver.auth.common.MPOAuthHelper.<clinit>(MPOAuthHelper.java:77)
```

Could it be related to the changed endpoint? if I start changing things in the radar-is.yml files I get 404, but that is when locally running `./gradlew check`

**Comment by Bdegraaf1234** [comment]
CI was failing because the servlet context path was changed in 7c8de2a269414679062e17be1eeac3e2c4650999 and the MPOAuthHelper class was not updated accordingly. fixed in 6895c3b5b570507109ecdb97f55faf4bf27fb0b2

**Review by blootsvoets — APPROVED** [review]
LGTM

**Pull request merged**
